# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Push - Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload jar to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HCCore.jar
          path: build/libs/HCCore-Shadow-*.jar
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    if: github.ref == 'refs/heads/master' && github.repository == 'hackclub/HCCore' && github.event_name == 'push'
#    steps:
#    - name: Download jar
#      uses: actions/download-artifact@v2
#      with:
#        name: HCCore-1.0.0.jar
#    - name: Add SSH key
#      run: mkdir $HOME/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa && chmod 400 $HOME/.ssh/id_rsa && ssh-keyscan -H mc.hackclub.com >> ~/.ssh/known_hosts
#    - name: Copy jar
#      run: scp HCCore-1.0.0.jar minecraft@mc.hackclub.com:/opt/minecraft/server/plugins/HCCore-1.0.0.jar
#    - name: Run reboot script
#      run: ssh minecraft@mc.hackclub.com /opt/minecraft/restart.sh

