name: HCCore
on:
  push:
    branches:
      - '*'
    tags:
      - v*.*.*
      - v*.*.*-rc.*
  pull_request:

jobs:
  validation:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
  build:
    if: (!startsWith(github.ref, 'refs/tags/v'))
    needs: validation
    runs-on: ubuntu-latest
    name: Gradle Build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          java-package: jdk
      - uses: actions/cache@v3
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/dependency-locks/*.lockfile') }}
          restore-keys: |
            - ${{ runner.os }}-gradle-
      - uses: actions/cache@v3
        id: gradle-wrapper-cache
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('gradle/wrapper/*') }}
          restore-keys: |
            - ${{ runner.os }}-gradlewrapper-
      - name: Gradle build
        run: ./gradlew --build-cache --info --stacktrace build -Prelease.state=dev
      - name: Upload jar to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HCCore.jar
          path: build/libs/HCCore-Shadow-*.jar
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: validation
    runs-on: ubuntu-latest
    name: Gradle Build Release
    outputs:
      release-assets: steps..outputs.assets
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          java-package: jdk
      - uses: actions/cache@v3
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/dependency-locks/*.lockfile') }}
          restore-keys: |
            - ${{ runner.os }}-gradle-
      - uses: actions/cache@v3
        id: gradle-wrapper-cache
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('gradle/wrapper/*') }}
          restore-keys: |
            - ${{ runner.os }}-gradlewrapper-
      - name: Publish candidate
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          contains(github.ref, '-rc.')
        run: ./gradlew --build-cache --info --stacktrace -Prelease.useLastTag=true candidate
      - name: Publish release
        if: |
          startsWith(github.ref, 'refs/tags/v') &&
          (!contains(github.ref, '-rc.'))
        run: ./gradlew --build-cache --info --stacktrace -Prelease.useLastTag=true final
      - name: Upload jar to build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: HCCore.jar
          path: build/libs/HCCore-Shadow-*.jar
      - name: Release
        id: add-gh-release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{github.ref}}"
          generate_release_notes: ${{ !(contains(github.ref, '-rc.')) }} # full releases only
          prerelease: ${{ contains(github.ref, '-rc.') }}
          files: "build/libs/HCCore-Shadow-*.jar"

  deploy:
    if: |
      startsWith(github.ref, 'refs/tags/v') &&
      (!contains(github.ref, '-rc.'))
    needs: release
    runs-on: ubuntu-latest
    name: Deploy to Production Server
    steps:
      - name: Download released version
        uses: actions/download-artifact@v3
        with:
          name: HCCore.jar
      - name: Get SSH key
        env:
          DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        run: echo $DEPLOY_SSH_PRIVATE_KEY > hackclub_minecraft_deploy
      - name: SCP Deploy
        run: "echo 'put HCCore/HCCore-Shadow-*.jar /plugins/update/' | sftp -vvv -i ./hackclub_minecraft_deploy -b - sftp://mc-hc-deployker.89c06257@hebra.365hosts.network:60022
"


